version: "3.7"
services:
  calculator:
    container_name: calculator
    labels:
      app: kubernetes-calculator
    build:
      context: services/calculator
      dockerfile: Dockerfile
    image: "pexers/calculator:${TAG}"
    ports:
      - 80:80
    links:  # Avoids to write hardcoded HTTP ports in calculator service
      - addition
      - division
      - multiplication
      - subtraction

  addition:
    container_name: addition
    labels:
      app: kubernetes-calculator
    build:
      context: services/addition
      dockerfile: Dockerfile
    image: "pexers/addition:${TAG}"
    ports:
      - 3000:80

  division:
    container_name: division
    labels:
      app: kubernetes-calculator
    build:
      context: services/division
      dockerfile: Dockerfile
    image: "pexers/division:${TAG}"
    ports:
      - 3001:80
      
  multiplication:
    container_name: multiplication
    labels:
      app: kubernetes-calculator
    build:
      context: services/multiplication
      dockerfile: Dockerfile
    image: "pexers/multiplication:${TAG}"
    ports:
      - 3002:80
      
  subtraction:
    container_name: subtraction
    labels:
      app: kubernetes-calculator
    build:
      context: services/subtraction
      dockerfile: Dockerfile
    image: "pexers/subtraction:${TAG}"
    ports:
      - 3003:80