apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-deployment
  labels:
    app: addition-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition-app
  template:
    metadata:
      labels:
        app: addition-app
    spec:
      containers:
      - name: addition-app
        image: pexers/addition:latest
        imagePullPolicy: Always   # Always pull the latest image from Docker Hub on start
        ports:
        - containerPort: 80       # The actual port where the container is running (=targetPort)
---
apiVersion: v1
kind: Service
metadata:
  name: addition
  labels:
    app: addition-app
spec:
  type: ClusterIP     # No external IP exposed
  ports:
  - protocol: TCP
    port: 80        # The exposed port within the cluster
    targetPort: 80  # The actual port where the container is running (=containerPort)
  selector: 
    app: addition-app
