apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  labels:
    app: calculator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: calculator-app
          image: pexers/calculator:latest
          imagePullPolicy: Always   # Always pull the latest image from Docker Hub on start
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calculator
  labels:
    app: calculator-app
spec:
  type: LoadBalancer  # Exposes an external IP to clients
  ports:
    - protocol: TCP
      port: 80          # The exposed port within the cluster
      targetPort: 8080  # The actual port where the container is running
  selector: 
    app: calculator-app
