apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication-deployment
  labels:
    app: multiplication-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplication-app
  template:
    metadata:
      labels:
        app: multiplication-app
    spec:
      containers:
      - name: multiplication-app
        image: pexers/multiplication:latest
        imagePullPolicy: Always   # Always pull the latest image from Docker Hub on start
        ports:
        - containerPort: 80       # The actual port where the container is running (=targetPort)
---
apiVersion: v1
kind: Service
metadata:
  name: multiplication
  labels:
    app: multiplication-app
spec:
  type: ClusterIP     # No external IP exposed
  ports:
  - protocol: TCP
    port: 80        # The exposed port within the cluster
    targetPort: 80  # The actual port where the container is running (=containerPort)
  selector: 
    app: multiplication-app
