apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtraction-deployment
  labels:
    app: subtraction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtraction-app
  template:
    metadata:
      labels:
        app: subtraction-app
    spec:
      containers:
      - name: subtraction-app
        image: pexers/subtraction:latest
        imagePullPolicy: Always   # Always pull the latest image from Docker Hub on start
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: subtraction
  labels:
    app: subtraction-app
spec:
  type: ClusterIP     # No external IP exposed
  ports:
  - protocol: TCP
    port: 80          # The exposed port within the cluster
    targetPort: 80  # The actual port where the container is running
  selector: 
    app: subtraction-app
