# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  #push:
    #branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  AZ_RESOURCE_GROUP: 'MyResourceGroup'
  AZ_CLUSTER: 'my-aks-cluster'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: pexers/calculator-base:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install dependencies & Test
      run: |
        npm i
        npm run test
  push-to-docker-hub:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Assign commit SHA to TAG environment variable
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV  
    - name: Login to Docker
      run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PWD }}
    - name: Build & Push services
      run: |
        docker compose build
        docker compose push --quiet
    - name: Logout of Docker
      run: docker logout
  deploy-to-aks:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-cli:latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install kubectl
      run: az aks install-cli
    - name: Login in Azure & Save credentials
      run: |
        az login --tenant ${{ secrets.AZ_TENANT_ID }} -u ${{ secrets.AZ_USER }} -p "${{ secrets.AZ_PWD }}" --output none
        az aks get-credentials --resource-group $AZ_RESOURCE_GROUP --name $AZ_CLUSTER
    - name: Deploy application to Kubernetes
      run: |
        kubectl apply -f pods
        kubectl rollout restart deploy
        kubectl get pods
        kubectl get services
    - name: Logout of Azure
      run: az logout
