# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: pexers/calculator-base:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install dependencies & Test
      run: |
        npm i
        npm run test
  push-to-docker-hub:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Login to Docker
      run: docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PWD }}
    - name: Build & Push services
      run: |
        docker compose build
        docker compose push --quiet
    - name: Logout of Docker
      run: docker logout
